spring:
  application:
    name: yapily
  threads:
    virtual:
      enabled: true
  cloud:
    vault:
      uri: http://localhost:8200
      token: root-token
      scheme: http
      kv:
        enabled: true
        backend: secret
        default-context: yapily-middleware

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port : 8081
